#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Тестовый скрипт для демонстрации TeleShop Tunnel GUI
"""

import time
import os
import subprocess
import re

def test_tunnel_creation():
    """Тест создания туннеля через командную строку"""
    print("=== Тест создания туннеля ===")
    print("Запускаю npx localtunnel --port 3000...")
    
    try:
        # Запускаем туннель
        process = subprocess.Popen(
            ['npx', 'localtunnel', '--port', '3000'],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=os.getcwd()
        )
        
        print("Ожидание получения URL...")
        
        # Ждем URL максимум 15 секунд
        for i in range(15):
            if process.poll() is not None:
                break
                
            line = process.stdout.readline()
            if line:
                print(f"Output: {line.strip()}")
                
                # Ищем URL
                match = re.search(r'your url is: (https://[^\s]+)', line)
                if match:
                    tunnel_url = match.group(1)
                    print(f"✅ Туннель создан: {tunnel_url}")
                    
                    # Создаем .env.local файл
                    env_path = os.path.join("01-user-dashboard", ".env.local")
                    with open(env_path, 'w', encoding='utf-8') as f:
                        f.write("# Auto-generated by Test Script\n")
                        f.write(f"NEXT_PUBLIC_TUNNEL_URL={tunnel_url}\n")
                    
                    print(f"✅ Конфигурация сохранена: {env_path}")
                    return tunnel_url
            
            time.sleep(1)
        
        print("❌ Не удалось получить URL за 15 секунд")
        return None
        
    except Exception as e:
        print(f"❌ Ошибка: {e}")
        return None

def test_component_status():
    """Проверка статуса компонентов"""
    print("\n=== Проверка компонентов ===")
    
    # Проверяем процессы
    result = subprocess.run(['tasklist'], capture_output=True, text=True)
    processes = result.stdout
    
    components = {
        'python.exe': 'Python процессы',
        'node.exe': 'Node.js процессы', 
        'npm.exe': 'NPM процессы'
    }
    
    for process, description in components.items():
        if process in processes:
            print(f"✅ {description}: найдены")
        else:
            print(f"❌ {description}: не найдены")

def test_env_file():
    """Проверка .env.local файла"""
    print("\n=== Проверка конфигурации ===")
    
    env_path = os.path.join("01-user-dashboard", ".env.local")
    
    if os.path.exists(env_path):
        print(f"✅ Файл {env_path} существует")
        
        with open(env_path, 'r', encoding='utf-8') as f:
            content = f.read()
            print("Содержимое:")
            print(content)
    else:
        print(f"❌ Файл {env_path} не найден")

def main():
    print("🌐 TeleShop Tunnel GUI - Тестирование функций")
    print("=" * 50)
    
    # Тест 1: Проверка статуса компонентов
    test_component_status()
    
    # Тест 2: Проверка конфигурации
    test_env_file()
    
    # Тест 3: Попытка создания туннеля
    print("\nХотите протестировать создание туннеля? (y/n): ", end="")
    choice = input().lower().strip()
    
    if choice in ['y', 'yes', 'да', 'д']:
        tunnel_url = test_tunnel_creation()
        if tunnel_url:
            print(f"\n🎉 Тест успешен! URL: {tunnel_url}")
        else:
            print("\n❌ Тест не удался")
    
    print("\n" + "=" * 50)
    print("Тестирование завершено!")

if __name__ == "__main__":
    main() 