@echo off
title TeleShop Auto Tunnel Launcher
color 0A

echo.
echo ====================================================
echo         🚀 TeleShop Auto Tunnel Launcher
echo ====================================================
echo.
echo Автоматический процесс:
echo  1. 🌐 Создание туннеля
echo  2. 📋 Получение публичного URL
echo  3. ⚙️  Применение URL к конфигурации
echo  4. 🚀 Запуск всех компонентов
echo.
pause

echo.
echo 🌐 Шаг 1: Создаем туннель для порта 3000...

:: Создаем временный файл для URL
set TEMP_URL_FILE=%TEMP%\teleshop_url.txt

:: Запускаем туннель в фоне и сохраняем URL
echo Запускаем локальный туннель...
start /B cmd /c "npx localtunnel --port 3000 > %TEMP_URL_FILE% 2>&1"

:: Ждем появления URL (максимум 30 секунд)
echo Ожидание получения URL...
set /a counter=0
:WAIT_FOR_URL
timeout /t 2 /nobreak >nul
set /a counter+=1
if exist %TEMP_URL_FILE% (
    findstr "your url is:" %TEMP_URL_FILE% >nul
    if !errorlevel! equ 0 goto URL_FOUND
)
if %counter% lss 15 goto WAIT_FOR_URL

echo ❌ Не удалось получить URL за 30 секунд
pause
exit /b 1

:URL_FOUND
:: Извлекаем URL из файла
for /f "tokens=4" %%i in ('findstr "your url is:" %TEMP_URL_FILE%') do set PUBLIC_URL=%%i

if "%PUBLIC_URL%"=="" (
    echo ❌ Не удалось извлечь URL
    pause
    exit /b 1
)

echo.
echo ✅ Получен публичный URL: %PUBLIC_URL%
echo.

echo ⚙️  Шаг 2: Применяем URL к конфигурации...

:: Создаем .env.local файл с публичным URL (только для фронтенда)
echo # Auto-generated by TeleShop Auto Tunnel Launcher > 01-user-dashboard\.env.local
echo NEXT_PUBLIC_TUNNEL_URL=%PUBLIC_URL% >> 01-user-dashboard\.env.local

echo ✅ Конфигурация обновлена!
echo   - Frontend URL: %PUBLIC_URL%
echo   - Backend API: localhost:8000 (остается локальным)
echo.

echo 🚀 Шаг 3: Запускаем все компоненты...
echo.

:: Запускаем Auth Bot
echo 🤖 Запускаем Auth Bot...
start "TeleShop Auth Bot" cmd /k "cd auth-bot && python simple_auth_bot.py"
timeout /t 3 /nobreak >nul

:: Запускаем Backend API
echo 🔧 Запускаем Backend API...
start "TeleShop Backend API" cmd /k "cd 05-server-launchers\main && python main_secure_fixed.py"
timeout /t 5 /nobreak >nul

:: Запускаем Frontend
echo 🌐 Запускаем Frontend...
start "TeleShop Frontend" cmd /k "cd 01-user-dashboard && npm run dev"
timeout /t 3 /nobreak >nul

echo.
echo ====================================================
echo               ✅ TeleShop запущен!
echo ====================================================
echo.
echo 🌐 Публичная ссылка: %PUBLIC_URL%
echo.
echo 📋 Поделитесь этой ссылкой с пользователями
echo.
echo 🛑 Для остановки закройте все окна
echo.

:: Очищаем временный файл
del %TEMP_URL_FILE% 2>nul

echo Открываем браузер...
start %PUBLIC_URL%

pause 